# Generated by Django 3.0.3 on 2020-05-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, help_text='Móvil de contacto', max_length=20, null=True, verbose_name='Móvil')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono')),
                ('address1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Calle/No.')),
                ('address2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Entre calles/Rpto/otros')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OlimpresPeople.City', verbose_name='Ciudad')),
            ],
        ),
    ]
