# Generated by Django 3.0.7 on 2020-06-20 22:50

import OlimpresPeople.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OlimpresPeople', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=OlimpresPeople.models.Partner.set_partner_avatar_name),
        ),
        migrations.AddField(
            model_name='partner',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
