# Generated by Django 3.0.7 on 2020-06-14 22:52

import OlimpresPeople.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpresPeople', '0002_auto_20200613_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='partner',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=OlimpresPeople.models.Partner.content_file_name),
        ),
    ]
