# Generated by Django 3.0.3 on 2020-05-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpresStock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.FloatField(default=5, verbose_name='Precio base'),
            preserve_default=False,
        ),
    ]
