# Generated by Django 3.0.3 on 2020-05-24 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpresStock', '0004_auto_20200523_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio base'),
        ),
    ]
